### ISSUE TITLE
Not able to download dependency

### ISSUE THREAD

**Issue by neelkanth3186** [Ingenico-ePayments/connect-sdk-java#1]
Hi , 
I am not able to download the dependency using maven or sbt. It seems the jar is not available in maven central repository. Can someone please check this.

**Comment by rob-spoor** [comment]
You are right, this is still work-in-progress. You'll have to manually install the SDK in a site-local Nexus or in a local repository.

The former can be achieved using the Maven deploy plugin (`mvn deploy:deploy-file`, checkout its flags at http://maven.apache.org/plugins/maven-deploy-plugin/deploy-file-mojo.html), the latter by using `mvn clean install` instead of `mvn clean package`.

**Comment by ebomcke-ingenico** [comment]
Hi,
The jar will be published in the central repository in the coming month, I'll update this issue when it has been done.

**Comment by ebomcke-ingenico** [comment]
Done, see https://repo1.maven.org/maven2/com/ingenico/connect/gateway/connect-sdk-java/.
